---

tomcat_ver: 9.0.30                        
ui_manager_user: manager                   
ui_manager_pass: Str0ngManagerP@ssw3rd      
ui_admin_username: admin                   
ui_admin_pass: Str0ngAdminP@ssw3rd      
tomcat_archive_url: https://archive.apache.org/dist/tomcat/tomcat-9/v{{ tomcat_ver }}/bin/apache-tomcat-{{ tomcat_ver }}.tar.gz
tomcat_archive_dest: /tmp/apache-tomcat-{{ tomcat_ver }}.tar.gz
